# Generated by Django 4.1.3 on 2022-11-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_alter_usuario_data_criacao_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='matricula',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='inativo',
            field=models.BooleanField(default='False'),
        ),
    ]
