# Generated by Django 4.1.3 on 2022-11-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0004_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_avaliacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recursos_humanos.usuario')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recursos_humanos.usuario')),
            ],
        ),
    ]
