# Generated by Django 4.1.3 on 2022-11-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_delete_meritosusuario'),
        ('recursos_humanos', '0006_classe_diretoria_gerencia_grupo_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='meritos',
            field=models.ManyToManyField(to='avaliacao.fatordesempenhomerito'),
        ),
    ]
