# Generated by Django 4.1.3 on 2022-11-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_delete_meritosusuario'),
        ('recursos_humanos', '0007_usuario_meritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='demeritos',
            field=models.ManyToManyField(to='avaliacao.fatordesempenhodemerito'),
        ),
    ]
