# Generated by Django 4.1.3 on 2022-11-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0008_usuario_demeritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='efetivo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='inativo',
            field=models.BooleanField(null=True),
        ),
    ]
