# Generated by Django 4.1.3 on 2022-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_alter_fatordesempenhodemerito_fator'),
        ('recursos_humanos', '0009_alter_usuario_efetivo_alter_usuario_inativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='demeritos',
            field=models.ManyToManyField(blank=True, default='', to='avaliacao.fatordesempenhodemerito'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='efetivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='inativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='meritos',
            field=models.ManyToManyField(blank=True, default='', to='avaliacao.fatordesempenhomerito'),
        ),
    ]
