# Generated by Django 4.1.3 on 2022-11-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_alter_fatordesempenhodemerito_fator'),
        ('recursos_humanos', '0010_alter_usuario_demeritos_alter_usuario_efetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, to='avaliacao.avaliacaodesempenho'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='demeritos',
            field=models.ManyToManyField(blank=True, to='avaliacao.fatordesempenhodemerito'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='meritos',
            field=models.ManyToManyField(blank=True, to='avaliacao.fatordesempenhomerito'),
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
