# Generated by Django 4.1.3 on 2022-11-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_alter_fatordesempenhodemerito_fator'),
        ('recursos_humanos', '0010_alter_usuario_demeritos_alter_usuario_efetivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='classe',
            field=models.CharField(choices=[('chefe', 'Chefe'), ('gerente', 'Gerente'), ('empregado', 'Empregado'), ('recursos_humanos', 'Recursos Humanos')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='demeritos',
            field=models.ManyToManyField(blank=True, to='avaliacao.fatordesempenhodemerito'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='diretoria',
            field=models.CharField(choices=[('diraf', 'Diretoria Administrativa Financeira'), ('dides', 'Diretoria de Desenvolvimento de Sistemas'), ('dirad', 'Diretoria de Alto Desempenho'), ('ditec', 'Diretoria de Tecnologia da Informação e Comunicação')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(choices=[('presidente', 'Presidente'), ('diretos', 'Diretor'), ('gerente', 'Gerente'), ('chefe', 'Chefe'), ('colaborador', 'Colaborador'), ('cedido', 'Cedido a outro orgão'), ('recursos_humanos', 'Recursos Humanos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gerencia',
            field=models.CharField(choices=[('adminstrativa', 'Adminstrativa'), ('financeira', 'Financeira'), ('negocios_prospeccao', 'Negócios e Prospecção'), ('treinamento', 'Treinamento'), ('recursos_humanos', 'Recursos Humanos')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='meritos',
            field=models.ManyToManyField(blank=True, to='avaliacao.fatordesempenhomerito'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(choices=[('i', 'I'), ('ii', 'II'), ('iii', 'III'), ('iv', 'IV'), ('v', 'V'), ('vi', 'VI'), ('vii', 'VII'), ('viii', 'VIII'), ('ix', 'IX'), ('x', 'X'), ('xi', 'XI'), ('xii', 'XII')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Diretoria',
        ),
        migrations.DeleteModel(
            name='Gerencia',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Nivel',
        ),
    ]
