# Generated by Django 4.1.3 on 2022-11-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0011_remove_usuario_grupo_alter_usuario_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='classe',
            field=models.CharField(choices=[('classe1', 'Classe 1'), ('classe2', 'Classe 2'), ('classe3', 'Classe 3')], max_length=20),
        ),
    ]
