# Generated by Django 4.1.3 on 2022-11-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0011_usuario_avaliacoes_alter_usuario_demeritos_and_more'),
        ('recursos_humanos', '0012_alter_usuario_classe'),
    ]

    operations = [
    ]
