# Generated by Django 4.1.3 on 2022-11-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0013_merge_20221124_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diretoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerencia', models.CharField(max_length=100)),
                ('diretoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.diretoria')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='diretoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.diretoria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gerencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.gerencia'),
        ),
    ]
