# Generated by Django 4.1.3 on 2022-11-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0014_diretoria_gerencia_alter_usuario_diretoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diretoria',
            name='sigla',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
