# Generated by Django 4.1.3 on 2022-11-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0015_diretoria_sigla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerencia',
            options={'verbose_name': 'Gerência'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(blank=True, choices=[('', '----'), ('i', 'I'), ('ii', 'II'), ('iii', 'III'), ('iv', 'IV'), ('v', 'V'), ('vi', 'VI'), ('vii', 'VII'), ('viii', 'VIII'), ('ix', 'IX'), ('x', 'X'), ('xi', 'XI'), ('xii', 'XII')], max_length=5, null=True),
        ),
    ]
