# Generated by Django 4.1.3 on 2022-11-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0016_alter_gerencia_options_alter_usuario_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ultima_avaliacao',
            new_name='data_ultima_avaliacao',
        ),
    ]
