# Generated by Django 4.1.3 on 2022-11-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0017_rename_ultima_avaliacao_usuario_data_ultima_avaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='data_exclusao_usuario',
            new_name='data_inativacao_usuario',
        ),
    ]
