# Generated by Django 4.1.3 on 2022-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0018_rename_data_exclusao_usuario_usuario_data_inativacao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_admissao_usuario',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='setor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
