# Generated by Django 4.1.3 on 2022-11-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos_humanos', '0006_classe_diretoria_gerencia_grupo_nivel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FatorDesempenhoDemerito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator', models.TextField()),
            ],
            options={
                'verbose_name': 'Fator de Desempenho Demeritório',
                'verbose_name_plural': 'Fator de Desempenho Demeritórios',
            },
        ),
        migrations.CreateModel(
            name='FatorDesempenhoMerito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator', models.TextField(blank=True, null=True)),
                ('nome', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.usuario')),
            ],
            options={
                'verbose_name': 'Fator de Desempenho Meritório',
                'verbose_name_plural': 'Fator de Desempenho Meritórios',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao_otima', models.TextField()),
                ('avaliacao_boa', models.TextField()),
                ('avaliacao_regular', models.TextField()),
                ('avaliacao_insuficiente', models.TextField()),
                ('categoria_avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacao.categoria')),
            ],
            options={
                'verbose_name': 'Avaliação de Desempenho',
                'verbose_name_plural': 'Avaliações de Desempenho',
            },
        ),
    ]
