# Generated by Django 4.1.3 on 2022-11-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_classe_diretoria_gerencia_grupo_nivel_and_more'),
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatordesempenhomerito',
            options={'verbose_name': 'Fator de Desempenho Meritório'},
        ),
        migrations.RemoveField(
            model_name='fatordesempenhomerito',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='fatordesempenhomerito',
            name='usuario',
        ),
        migrations.CreateModel(
            name='MeritosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator', models.ManyToManyField(to='avaliacao.fatordesempenhomerito')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.usuario')),
            ],
        ),
    ]
