# Generated by Django 4.1.3 on 2022-11-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_alter_fatordesempenhomerito_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeritosUsuario',
        ),
    ]
