# Generated by Django 4.1.3 on 2022-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_delete_meritosusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatordesempenhodemerito',
            name='fator',
            field=models.TextField(blank=True, null=True),
        ),
    ]
